In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
dataset = pd.read_csv('../Data/heart.csv')

In [3]:
dataset.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

### preprocessing

In [4]:
# be very careful as standarization is not applicable for categorical datas.. 
# for example here sex

In [5]:
dataset.shape

(303, 14)

In [6]:
dataset.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
dataset.groupby('target').size()

# 1 --> defective heart
# 0 --> normal heart

target
0    138
1    165
dtype: int64

In [8]:
X = dataset.iloc[:, 0:13]
# dataset.drop(column='target', axis=1)
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [9]:
Y = dataset.iloc[:, -1]
Y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

### Train test split

In [10]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,
                                                 test_size=0.15,
                                                 random_state=2,
                                                 stratify=Y)

In [11]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (257, 13) (46, 13)

### Comparing the performance of the models

In [12]:
# list of models
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [13]:
def compare_models_train_test():

  for model in models:

    # training the model
    model.fit(X_train, Y_train)
    
    # evaluating the model
    test_data_prediction = model.predict(X_test)
    accuracy = accuracy_score(Y_test, test_data_prediction)

    print('Accuracy score of the ', model, ' = ', accuracy)

In [14]:
compare_models_train_test()

Accuracy score of the  LogisticRegression(max_iter=1000)  =  0.7608695652173914
Accuracy score of the  SVC(kernel='linear')  =  0.8260869565217391
Accuracy score of the  KNeighborsClassifier()  =  0.5652173913043478
Accuracy score of the  RandomForestClassifier()  =  0.7391304347826086

### Cross Validation
<img src='../images/cross_val_image.png'>

Logistic Regression

In [15]:
cv_score_lr = cross_val_score(LogisticRegression(max_iter=1000),X,Y,cv=5)
# if we mention the value of cv instead of using kfold we use stratified k-fold method
print(cv_score_lr)

mean_accuracy_lr = sum(cv_score_lr)/len(cv_score_lr)
mean_accuracy_lr *= 100
mean_accuracy_lr = round(mean_accuracy_lr,2)
print(f"{mean_accuracy_lr}%")

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
82.83%

SVC(support Vector Classifier)

In [16]:
cv_score_sv = cross_val_score(SVC(kernel='linear'),X,Y,cv=5)
# if we mention the value of cv instead of using kfold we use stratified k-fold method
print(cv_score_sv)

mean_accuracy_sv = sum(cv_score_sv)/len(cv_score_sv)
mean_accuracy_sv *= 100
mean_accuracy_sv = round(mean_accuracy_sv,2)
print(f"{mean_accuracy_sv}%")

[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
82.83%

KNN(k nearest neighbour)

In [17]:
cv_score_knn = cross_val_score(KNeighborsClassifier(),X,Y,cv=5)
# if we mention the value of cv instead of using kfold we use stratified k-fold method
print(cv_score_knn)

mean_accuracy_knn = sum(cv_score_knn)/len(cv_score_knn)
mean_accuracy_knn *= 100
mean_accuracy_knn = round(mean_accuracy_knn,2)
print(f"{mean_accuracy_knn}%")

[0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
64.39%

Random Forest Classifier

In [18]:
cv_score_rfc = cross_val_score(RandomForestClassifier(),X,Y,cv=5)
# if we mention the value of cv instead of using kfold we use stratified k-fold method
print(cv_score_rfc)

mean_accuracy_rfc = sum(cv_score_rfc)/len(cv_score_rfc)
mean_accuracy_rfc *= 100
mean_accuracy_rfc = round(mean_accuracy_rfc,2)
print(f"{mean_accuracy_rfc}%")

[0.80327869 0.90163934 0.80327869 0.81666667 0.78333333]
82.16%

In [19]:
from cross_validation import my_CV

In [20]:
my_CV(models,X,Y)

Cross validation accuracy for =  LogisticRegression(max_iter=1000) = [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
Accuracy percentage for the model =  LogisticRegression(max_iter=1000) = 82.83
-----------------------------------------------------------------------
Cross validation accuracy for =  SVC(kernel='linear') = [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
Accuracy percentage for the model =  SVC(kernel='linear') = 82.83
-----------------------------------------------------------------------
Cross validation accuracy for =  KNeighborsClassifier() = [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
Accuracy percentage for the model =  KNeighborsClassifier() = 64.39
-----------------------------------------------------------------------
Cross validation accuracy for =  RandomForestClassifier() = [0.85245902 0.86885246 0.81967213 0.8        0.78333333]
Accuracy percentage for the model =  RandomForestClassifier() = 82.49
-----------------------------------------------------------------------