In [1]:
import pandas as pd
pd.__version__

'2.3.3'

In [ ]:
# structure of iloc
# df.loc[rows, columns]

# series == 1d array
# dataframe == 2d matrix
# pythons version of microsoft excel

# loc ==  location by label
# to print or access or change we use loc property
# loc and iloc only works on the index not only the normal columns

# iloc == integer location 0 indexed

In [ ]:
data = [101.1,102.4,103.3] # list ---> converted to series
series = pd.Series(data, index=['a','b','c'])
series

a    101.1
b    102.4
c    103.3
dtype: float64

In [3]:
print(series.loc['a'])

series.loc['a'] = 199.1
print(series.iloc[0])

101.1
199.1

In [ ]:
fruits = { 'apples':[3,2,0,1] , 'oranges':[0,3,7,2] , "angur":[1,0,2,1] , 'bananas':[4,3,5,7] } # dictionary

df = pd.DataFrame(fruits)
df
# we can use dict key as labels

   apples  oranges  angur  bananas
0       3        0      1        4
1       2        3      0        3
2       0        7      2        5
3       1        2      1        7

In [5]:
series = pd.Series(fruits)
series

apples     [3, 2, 0, 1]
oranges    [0, 3, 7, 2]
angur      [1, 0, 2, 1]
bananas    [4, 3, 5, 7]
dtype: object

In [ ]:
series.loc['oranges'].append(32)

[0, 3, 7, 2, 32, 32, 32]

In [20]:
print(series['oranges'])
print(type(series['oranges']))
print(type(series))

[0, 3, 7, 2, 32, 32, 32]
<class 'list'>
<class 'pandas.core.series.Series'>

In [21]:
print(df['oranges'])
print(type(df['oranges']))
print(type(df))

0    0
1    3
2    7
3    2
Name: oranges, dtype: int64
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [22]:
print(series[series.apply(sum) < 15])

apples    [3, 2, 0, 1]
angur     [1, 0, 2, 1]
dtype: object

In [23]:
company_info = {
    'name': ['sonu','rushi','loki','anisha'],
    'age': [12,11,13,44],
    'isAdult': [False, False, False, True]
}

df = pd.DataFrame(company_info, index= ['employee1','employee2','employee3','employee4'])
print(df)

             name  age  isAdult
employee1    sonu   12    False
employee2   rushi   11    False
employee3    loki   13    False
employee4  anisha   44     True

In [24]:
# adding a new column
df['job'] = ['student','wall-painter','mechanic','artist']
df

             name  age  isAdult           job
employee1    sonu   12    False       student
employee2   rushi   11    False  wall-painter
employee3    loki   13    False      mechanic
employee4  anisha   44     True        artist

In [26]:
# adding a new rows
new_rows = pd.DataFrame([ {'name':'crabs', 'age':21, 'isAdult':True, 'job':'manager'},
                          {'name':'squid', 'age':17, 'isAdult':False, 'job':'Bae-Dancer'}],
                        index=['employee5','employee6'])
df = pd.concat([df,new_rows])
df

             name  age  isAdult           job
employee1    sonu   12    False       student
employee2   rushi   11    False  wall-painter
employee3    loki   13    False      mechanic
employee4  anisha   44     True        artist
employee5   crabs   21     True       manager
employee6   squid   17    False    Bae-Dancer

## working with CSV(comma seperated value) files

In [47]:
df = pd.read_csv('../../Data/pokemon.csv') # add index_col = 'Name'

In [48]:
df.head()

   No       Name  Type1   Type2  Height  Weight  Legendary
0   1  Bulbasaur  Grass  Poison     0.7     6.9          0
1   2    Ivysaur  Grass  Poison     1.0    13.0          0
2   3   Venusaur  Grass  Poison     2.0   100.0          0
3   3   Venusaur  Grass  Poison     2.0   100.0          0
4   3   Venusaur  Grass  Poison     2.0   100.0          0

In [54]:
df = df.drop(columns='No')
df.head()

        Name  Type1   Type2  Height  Weight  Legendary
0  Bulbasaur  Grass  Poison     0.7     6.9          0
1    Ivysaur  Grass  Poison     1.0    13.0          0
2   Venusaur  Grass  Poison     2.0   100.0          0
3   Venusaur  Grass  Poison     2.0   100.0          0
4   Venusaur  Grass  Poison     2.0   100.0          0

In [55]:
df['Type1']

0        Grass
1        Grass
2        Grass
3        Grass
4        Grass
        ...
153       Fire
154     Dragon
155     Dragon
156     Dragon
157    Psychic
Name: Type1, Length: 158, dtype: object

In [56]:
df[['Name','Type1','Type2']]

          Name    Type1   Type2
0    Bulbasaur    Grass  Poison
1      Ivysaur    Grass  Poison
2     Venusaur    Grass  Poison
3     Venusaur    Grass  Poison
4     Venusaur    Grass  Poison
..         ...      ...     ...
153    Moltres     Fire  Flying
154    Dratini   Dragon     NaN
155  Dragonair   Dragon     NaN
156  Dragonite   Dragon  Flying
157     Mewtwo  Psychic     NaN

[158 rows x 3 columns]

In [ ]:
df[df['Name'] == 'Pikachu']
# or 
# df.loc[df['Name'] == 'Squirtle']

# loc['value'] → searches index labels
# df['col'] == value → searches inside a column

       Name     Type1 Type2  Height  Weight  Legendary
29  Pikachu  Electric   NaN     0.4     6.0          0

In [58]:
df.set_index('Name', inplace=True)
# Modify the original dataframe directly.
df.head()

           Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur  Grass  Poison     0.7     6.9          0
Ivysaur    Grass  Poison     1.0    13.0          0
Venusaur   Grass  Poison     2.0   100.0          0
Venusaur   Grass  Poison     2.0   100.0          0
Venusaur   Grass  Poison     2.0   100.0          0

In [ ]:
df.loc['Charmeleon':'Pidgeot', ['Type1','Height','Weight']]
# df.loc[rows,cols]
# select rows from Charmeleon to Charmeleon inclusive and only show these columns

             Type1  Height  Weight
Name
Charmeleon    Fire     1.1    19.0
Charizard     Fire     1.7    90.5
Squirtle     Water     0.5     9.0
Squirtle     Water     0.5     9.0
Squirtle     Water     0.5     9.0
Wartortle    Water     1.0    22.5
Blastoise    Water     1.6    85.5
Caterpie       Bug     0.3     2.9
Metapod        Bug     0.7     9.9
Butterfree     Bug     1.1    32.0
Weedle         Bug     0.3     3.2
Kakuna         Bug     0.6    10.0
Beedrill       Bug     1.0    29.5
Pidgey      Normal     0.3     1.8
Pidgeotto   Normal     1.1    30.0
Pidgeot     Normal     1.5    39.5

In [ ]:
df.iloc[0:12:2]
# basic slicing like python same start, stop, step

            Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur   Grass  Poison     0.7     6.9          0
Venusaur    Grass  Poison     2.0   100.0          0
Venusaur    Grass  Poison     2.0   100.0          0
Charmeleon   Fire     NaN     1.1    19.0          0
Squirtle    Water     NaN     0.5     9.0          0
Squirtle    Water     NaN     0.5     9.0          0

In [62]:
# we can mention what columns we want as output besides slicing
df.iloc[0:12:2, 0:3]

            Type1   Type2  Height
Name
Bulbasaur   Grass  Poison     0.7
Venusaur    Grass  Poison     2.0
Venusaur    Grass  Poison     2.0
Charmeleon   Fire     NaN     1.1
Squirtle    Water     NaN     0.5
Squirtle    Water     NaN     0.5

### Filtering

In [64]:
tall_pokemon = df[df['Height'] > 2.0]

heavy_pokemon = df[df['Weight'] > 100.0]

water_pokemon = df[(df['Type1'] == 'Water') | (df['Type2'] == 'Water')]

fire_flying = df[(df['Type1'] == 'Fire') & (df['Type2'] == 'Flying')]
fire_flying

          Type1   Type2  Height  Weight  Legendary
Name
Charizard  Fire  Flying     1.7    90.5          0
Moltres    Fire  Flying     2.0    60.0          1

### Aggregate Function

In [70]:

# These aggregate function is applied to the whole dataframe
# print(df.mean(numeric_only=True))
# print(df.sum(numeric_only=True))
# print(df.min(numeric_only=True))
# print(df.max(numeric_only=True))
# print(df.count()) # count does not include null values

# single column
print(df["Height"].mean(numeric_only=True))
print(df["Height"].sum(numeric_only=True))
print(df["Height"].min(numeric_only=True))
print(df["Height"].max(numeric_only=True))
print(df["Height"].count()) # count does not include null values

1.2044303797468354
190.3
0.2
8.8
158

In [68]:
# groupby() splits the dataframe into groups based on a column.
# Here, rows are grouped according to the values in the "Type1" column.

group = df.groupby("Type1")

# No calculation happens yet.
# We must apply an aggregation operation like mean(), min(), max(), sum(), etc.

# Find the minimum Height value for each Type1 group
print(group["Height"].min())

# Example:
# Fire   -> minimum height among all Fire Pokémon
# Water  -> minimum height among all Water Pokémon

Type1
Bug         0.3
Dragon      1.8
Electric    0.3
Fairy       0.6
Fighting    0.5
Fire        0.6
Ghost       1.3
Grass       0.4
Ground      0.2
Ice         1.4
Normal      0.3
Poison      0.4
Psychic     0.9
Rock        0.4
Water       0.3
Name: Height, dtype: float64

### Data Cleaning
The process of removing incorrect,irrelivent and incomplete data.
75% of work done in pandas is for data cleaning

In [ ]:
# 1. drop irrelivent columns
df = df.drop(columns= ["No","Legendary"])

In [ ]:
# Handle missing data (NaN values)

# dropna() removes rows containing missing values.

# If any row has NaN in the "Type2" column,
# the entire row will be removed.
df = df.dropna(subset=["Type2"])


# fillna() replaces missing values instead of deleting rows.

# Here, all NaN values in the "Type2" column are replaced with the string "None".
df = df.fillna({"Type2": "None"})

In [71]:
# Fix inconsistent values in a column
# replace() changes specific values into new values.

# Here, values in the "Type1" column are converted
# into a consistent uppercase format.

df["Type1"] = df["Type1"].replace({
    "Grass": "GRASS",
    "Fire": "FIRE",
    "Water": "WATER"
})

# Example:
# Grass -> GRASS
# Fire  -> FIRE
# Water -> WATER

In [75]:
# 4. standarized text
df["Type2"] = df["Type2"].str.lower()
df.index = df.index.str.lower()
df.head()

           Type1   Type2  Height  Weight  Legendary
Name
bulbasaur  GRASS  poison     0.7     6.9          0
ivysaur    GRASS  poison     1.0    13.0          0
venusaur   GRASS  poison     2.0   100.0          0
venusaur   GRASS  poison     2.0   100.0          0
venusaur   GRASS  poison     2.0   100.0          0

In [ ]:
# 5. fix datatypes
df["Legendary"] = df["Legendary"].astype(bool)

In [ ]:
# 6. removing duplicate entries
df = df.drop_duplicates()
print(df)

In [76]:
print("Columns:", df.columns.tolist())
print("Index name:", df.index.name)
print("Index type:", type(df.index))
print(df.head())

Columns: ['Type1', 'Type2', 'Height', 'Weight', 'Legendary']
Index name: Name
Index type: <class 'pandas.core.indexes.base.Index'>
           Type1   Type2  Height  Weight  Legendary
Name
bulbasaur  GRASS  poison     0.7     6.9          0
ivysaur    GRASS  poison     1.0    13.0          0
venusaur   GRASS  poison     2.0   100.0          0
venusaur   GRASS  poison     2.0   100.0          0
venusaur   GRASS  poison     2.0   100.0          0

### Advanced Data cleaning

In [77]:
df = pd.read_excel("../../Data/Customer_Call_List.xlsx",index_col="CustomerID")
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
CustomerID,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
1007,Jeff,Winger,NaN,1209 South Street,No,No,False
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
1019,Creed,Braton,N/a,N/a,N/a,Yes,True
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [89]:
df = df.drop_duplicates()
# df = df.drop(columns= ["Not_Useful_Column"])

# df["Last_Name"] = df["Last_Name"].str.lstrip(".")
# df["Last_Name"] = df["Last_Name"].str.lstrip("/")
# df["Last_Name"] = df["Last_Name"].str.rstrip("_")
df["Last_Name"] = df["Last_Name"].str.strip("123./_")
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,NaN,1209 South Street,No,No
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
1019,Creed,Braton,N/a,N/a,N/a,Yes
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N