In [2]:
import pandas as pd
pd.__version__

'2.3.3'

series == 1d array<br>
dataframe == 2d matrix<br>
pythons version of microsift excel<br>
<br>
loc ==  location by label<br>
to print or access or change we use loc property<br>
<br>
iloc == integer location 0 indexed<br>

In [9]:
data = [101.1,102.4,103.3]
series = pd.Series(data, index=['a','b','c'])
print(series)
print(series.loc['a'])

series.loc['a'] = 199.1
print(series.iloc[0])

a    101.1
b    102.4
c    103.3
dtype: float64
101.1
199.1

In [6]:
fruits = { 'apples':[3,2,0,1] , 'oranges':[0,3,7,2] , "angur":[1,0,2,1] , 'bananas':[4,3,5,7] }
series = pd.Series(fruits)
df = pd.DataFrame(fruits)
print(df)
# we can use dict key as labels

series.loc['oranges'].append(32)
print(series)

print(series[series.apply(sum) < 15])

   apples  oranges  angur  bananas
0       3        0      1        4
1       2        3      0        3
2       0        7      2        5
3       1        2      1        7
apples         [3, 2, 0, 1]
oranges    [0, 3, 7, 2, 32]
angur          [1, 0, 2, 1]
bananas        [4, 3, 5, 7]
dtype: object
apples    [3, 2, 0, 1]
angur     [1, 0, 2, 1]
dtype: object

In [5]:
company_info = {
    'name': ['sonu','rushi','loki','anisha'],
    'age': [12,11,13,44],
    'isAdult': [False, False, False, True]
}

df = pd.DataFrame(company_info, index= ['employee1','employee2','employee3','employee4'])

# adding a new column
df['job'] = ['student','wall-painter','mechanic','artist']

# adding a new rows
new_rows = pd.DataFrame([ {'name':'crabs', 'age':21, 'isAdult':True, 'job':'manager'},
                          {'name':'squid', 'age':17, 'isAdult':False, 'job':'Bae-Dancer'}],
                        index=['employee5','employee6'])
print(new_rows)
print('\n\n')
df = pd.concat([df,new_rows])
print(df)

            name  age  isAdult         job
employee5  crabs   21     True     manager
employee6  squid   17    False  Bae-Dancer



             name  age  isAdult           job
employee1    sonu   12    False       student
employee2   rushi   11    False  wall-painter
employee3    loki   13    False      mechanic
employee4  anisha   44     True        artist
employee5   crabs   21     True       manager
employee6   squid   17    False    Bae-Dancer

#### working with CSV(comma seperated value) files

In [51]:
df = pd.read_csv('../Data/pokemon.csv', index_col='Name')

# SELECTION BY COLUMN
# print(df) # prints only truncated val to print all use df.to_string()
# print(df['Type1'])
# print(df.Name)
# print(df[['Name','Type1','Type2']].to_string())

# SELECTION BY ROWS
# we can set a specific column to serve as indexing like name
# df = pd.read_csv('../Data/pokemon.csv', index_col='Name')
# print(df.loc['Pikachu'])
# print("\n")
# print(df.loc['Charmeleon':'Pidgeot', ['Type1','Height','Weight']]) 
# print("\n")

# print(df.iloc[0:12:2]) # basic slicing same start,stop,step
# print("\n")

# # we can mention what columns we want as output besides slicing
# print(df.iloc[0:12:2, 0:3])


# pokemon search
# pokemon = input('Enter pokemon name: ')

# try:
#     print(df.loc[pokemon])
# except KeyError:
#     print(f"{pokemon} not found in the database")

### Filtering

In [26]:
tall_pokemon = df[df['Height'] > 2.0]
# print(tall_pokemon,end="\n\n")

heavy_pokemon = df[df['Weight'] > 100.0]
# print(heavy_pokemon,end="\n\n")

water_pokemon = df[(df['Type1'] == 'Water') |
                   (df['Type2'] == 'Water')]
# print(water_pokemon,end="\n\n")

fire_flying = df[(df['Type1'] == 'Fire') &
                 (df['Type2'] == 'Flying')]
print(fire_flying)

            No Type1   Type2  Height  Weight  Legendary
Name
Charizard    6  Fire  Flying     1.7    90.5          0
Moltres    146  Fire  Flying     2.0    60.0          1

### Aggregate Function

In [34]:

# These aggregate function is applied to the whole dataframe
# print(df.mean(numeric_only=True))
# print(df.sum(numeric_only=True))
# print(df.min(numeric_only=True))
# print(df.max(numeric_only=True))
# print(df.count()) # count does not include null values

# single column
print(df["Height"].mean())
print(df["Height"].sum())
print(df["Height"].min())
print(df["Height"].max())
print(df["Height"].count()) # count does not include null values

1.2
180.0
0.2
8.8
150

Reduce a set of values into a single summary values used to summerize and analize data often used with groupby() function

In [ ]:
group = df.groupby("Type1")
# I have split the data by Type1, but 
# I will not do anything until you tell me what operation to apply.

# print(group["Height"].mean())    
print(group["Height"].min())

Type1
Bug         0.3
Dragon      1.8
Electric    0.3
Fairy       0.6
Fighting    0.5
Fire        0.6
Ghost       1.3
Grass       0.4
Ground      0.2
Ice         1.4
Normal      0.3
Poison      0.4
Psychic     0.9
Rock        0.4
Water       0.3
Name: Height, dtype: float64

### Data Cleaning
The process of removing incorrect,irrelivent and incomplete data.
75% of work done in pandas is for data cleaning

In [60]:
# 1. drop irrelivent columns
# df = df.drop(columns= ["No","Legendary"])

# 2. handle mssing data -> dropna() -> drop if not available... 
# if type2 for any row has NaN then it drops the entire row
# df = df.dropna(subset= ["Type2"])
# df = df.fillna({"Type2":"None"})

# 3. fix any inconsistent value
# df["Type1"] = df["Type1"].replace({"Grass":"GRASS",
#                                    "Fire":"FIRE",
#                                    "Water":"WATER"})

# 4. standarized text
# df["Name"] = df["Name"].str.lower()
df.index = df.index.str.lower()


# 5. fix datatypes
df["Legendary"] = df["Legendary"].astype(bool)

# 6. removing duplicate entries
df = df.drop_duplicates()
print(df)

             No    Type1   Type2  Height  Weight  Legendary
Name
bulbasaur     1    GRASS  Poison     0.7     6.9      False
ivysaur       2    GRASS  Poison     1.0    13.0      False
venusaur      3    GRASS  Poison     2.0   100.0      False
charmander    4     FIRE    None     0.6     8.5      False
charmeleon    5     FIRE    None     1.1    19.0      False
...         ...      ...     ...     ...     ...        ...
moltres     146     FIRE  Flying     2.0    60.0       True
dratini     147   Dragon    None     1.8     3.3      False
dragonair   148   Dragon    None     4.0    16.5      False
dragonite   149   Dragon  Flying     2.2   210.0      False
mewtwo      150  Psychic    None     2.0   122.0       True

[150 rows x 6 columns]

In [59]:
print("Columns:", df.columns.tolist())
print("Index name:", df.index.name)
print("Index type:", type(df.index))
print(df.head())

Columns: ['No', 'Type1', 'Type2', 'Height', 'Weight', 'Legendary']
Index name: Name
Index type: <class 'pandas.core.indexes.base.Index'>
            No  Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur    1  GRASS  Poison     0.7     6.9      False
Ivysaur      2  GRASS  Poison     1.0    13.0      False
Venusaur     3  GRASS  Poison     2.0   100.0      False
Charmander   4   FIRE    None     0.6     8.5      False
Charmeleon   5   FIRE    None     1.1    19.0      False

### Advanced Data cleaning

In [86]:
df = pd.read_excel("../Data/Customer_Call_List.xlsx",index_col="CustomerID")
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
CustomerID,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
1007,Jeff,Winger,NaN,1209 South Street,No,No,False
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
1019,Creed,Braton,N/a,N/a,N/a,Yes,True
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [89]:
df = df.drop_duplicates()
# df = df.drop(columns= ["Not_Useful_Column"])

# df["Last_Name"] = df["Last_Name"].str.lstrip(".")
# df["Last_Name"] = df["Last_Name"].str.lstrip("/")
# df["Last_Name"] = df["Last_Name"].str.rstrip("_")
df["Last_Name"] = df["Last_Name"].str.strip("123./_")
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,NaN,1209 South Street,No,No
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
1019,Creed,Braton,N/a,N/a,N/a,Yes
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N